### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ifishzz** [super-l/superl-githack#2]
Traceback (most recent call last):
  File "superl-githack.py", line 138, in <module>
    save(url)
  File "superl-githack.py", line 84, in save
    content = getHtmlContent(url)
  File "superl-githack.py", line 51, in getHtmlContent
    response = urllib2.urlopen(req, timeout=30)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by samshuai** [comment]
+1

**Comment by RasAlGhul-1** [comment]
+1

**Comment by RasAlGhul-1** [comment]
+1

**Comment by shineme** [comment]
+1
